/* Save file generated by schematic_gui v0.65 */
module test;
    wire unnamedwire0;
    wire unnamedwire1;
    wire unnamedwire2;
    wire unnamedwire5;
    wire unnamedwire4;
    wire unnamedwire3;

    add inst_00(.op1(unnamedwire4),
        .op2(unnamedwire3),
        .res(unnamedwire5),
        .ci(unnamedwire2));

    mux2 inst_02(.d0(unnamedwire1),
        .d1(~unnamedwire1),
        .o(unnamedwire4),
        .s(unnamedwire2));

    clockedreg inst_01(.d(unnamedwire5),
        .q(unnamedwire0));

    initial begin
        $schematic_text("text_inst_00", "Csub");
        $schematic_setgatepos("text_inst_00", 380,220);
        $schematic_setgaterot("text_inst_00", 3);
        $schematic_text("text_inst_02", "OpB");
        $schematic_setgatepos("text_inst_02", 400,470);
        $schematic_text("text_inst_01", "OpA");
        $schematic_setgatepos("text_inst_01", 190,370);
        $schematic_setgatepos(inst_00, 460,340);
        $schematic_text("text_inst_03", "RESULT");
        $schematic_setgatepos("text_inst_03", 740,430);
        $schematic_setgatepos(inst_02, 330,330);
        $schematic_setgatepos(inst_01, 610,370);
        $schematic_startroute("text_inst_00.r");
        $schematic_junction(380, 330);
        $schematic_endroute(inst_02.s);
        $schematic_endroute(inst_00.ci);
        $schematic_popjunction;
        $schematic_startroute(inst_00.res);
        $schematic_endroute(inst_01.d);
        $schematic_startroute(inst_02.o);
        $schematic_endroute(inst_00.op1);
        $schematic_startroute(inst_00.op2);
        $schematic_endroute("text_inst_02.r");
        $schematic_startroute(inst_02.d0);
        $schematic_junction(290, 370);
        $schematic_fixed_junction(290, 390);
        $schematic_endroute(inst_02.d1);
        $schematic_popjunction;
        $schematic_endroute("text_inst_01.r");
        $schematic_popjunction;
        $schematic_startroute(inst_01.q);
        $schematic_endroute("text_inst_03.l");
    end
endmodule
